import 'package:flutter/material.dart';
import 'colors.dart';
class imageIcon{
  static ImageIcon heartIcon = ImageIcon(AssetImage('images/icon/Heart.png'),color: Colors_APP.color_primary);
  static ImageIcon notifiIcon = ImageIcon(AssetImage('images/icon/Notification.png'),color: Colors_APP.color_primary);
  static ImageIcon filterIcon = ImageIcon(AssetImage('images/icon/fillter.png'));
  static ImageIcon leftIcon = ImageIcon(AssetImage('images/icon/left.png'));
  static ImageIcon rightIcon = ImageIcon(AssetImage('images/icon/right.png'));
  static ImageIcon left2Icon = ImageIcon(AssetImage('images/icon/left2.png'));
  static ImageIcon right2Icon = ImageIcon(AssetImage('images/icon/right2.png'));
  static ImageIcon menuDarkIcon = ImageIcon(AssetImage('images/icon/menudark.png'));
  static ImageIcon menueLightIcon = ImageIcon(AssetImage('images/icon/menulight.png'));
  static ImageIcon homeIcon = ImageIcon(AssetImage('images/icon/home.png'),);
  static ImageIcon storyIcon = ImageIcon(AssetImage('images/icon/story.png'));
  static ImageIcon citiesIcon = ImageIcon(AssetImage('images/icon/cities.png'));
  static ImageIcon mapIcon = ImageIcon(AssetImage('images/icon/map.png'));
  static ImageIcon profileIcon = ImageIcon(AssetImage('images/icon/profile.png'),color:Colors.white);
  static ImageIcon settingIcon = ImageIcon(AssetImage('images/icon/setting.png'),color:Colors.white);
  static ImageIcon callingIcon = ImageIcon(AssetImage('images/icon/calling.png'),color:Colors.white);
  static ImageIcon callingIcon1 = ImageIcon(AssetImage('images/icon/calling.png'),color:Colors_APP.color_primary);
  static ImageIcon InfoIcon = ImageIcon(AssetImage('images/icon/Info.png'),color:Colors.white);
  static ImageIcon InfoIcon1 = ImageIcon(AssetImage('images/icon/Info.png'),color:Colors_APP.color_primary);
  static ImageIcon shareIcon = ImageIcon(AssetImage('images/icon/share.png'),color:Colors.white);
  static ImageIcon logoutIcon = ImageIcon(AssetImage('images/icon/logout.png'),color:Colors.white);
  static ImageIcon messageIcon = ImageIcon(AssetImage('images/icon/message.png'),color:Colors.white);
  static ImageIcon messageIcon1 = ImageIcon(AssetImage('images/icon/message.png'),color:Colors_APP.color_primary);
  static ImageIcon locationIcon = ImageIcon(AssetImage('images/icon/location.png'),color:Colors.white);
  static ImageIcon locationIcon1 = ImageIcon(AssetImage('images/icon/location.png'),color:Colors_APP.color_primary);
  static ImageIcon imageProfileIcon = ImageIcon(AssetImage('images/icon/imageProfile.png'));
  static ImageIcon heartFillIcon = ImageIcon(AssetImage('images/icon/heartFill.png'));
  static ImageIcon calenderIcon = ImageIcon(AssetImage('images/icon/calender.png'));
  static ImageIcon timeIcon = ImageIcon(AssetImage('images/icon/time.png'));
  static ImageIcon Degree360Icon = ImageIcon(AssetImage('images/icon/360Degree.png'),color: Colors.white,);
  static ImageIcon moreIcon = ImageIcon(AssetImage('images/icon/more.png'));
  static ImageIcon bottom= ImageIcon(AssetImage('images/icon/bottom.png'));
  static ImageIcon Arabia= ImageIcon(AssetImage('images/icon/Arabia.png'));
  static ImageIcon storyadd = ImageIcon(AssetImage('images/icon/Storyadd.png'),color:Colors.white);
  static ImageIcon about = ImageIcon(AssetImage('images/icon/about.png'),color:Colors.white);
  static ImageIcon delivery = ImageIcon(AssetImage('images/icon/Delivery.png'),color:Colors.white);
  static ImageIcon Chaticon = ImageIcon(AssetImage('images/icon/Chaticon.png'),color:Colors.white);
  static ImageIcon Category = ImageIcon(AssetImage('images/icon/Category.png'),color:Colors.white);
  static ImageIcon Send = ImageIcon(AssetImage('images/icon/Send.png'),color:Colors.white);
  static ImageIcon imagechat= ImageIcon(AssetImage('images/icon/Image.png'),color:Colors.white);
  static ImageIcon Paper= ImageIcon(AssetImage('images/icon/Paper.png'),color:Colors.white);
  static ImageIcon voice= ImageIcon(AssetImage('images/icon/Voice2.png'),color:Colors.white);
  static ImageIcon camera= ImageIcon(AssetImage('images/icon/Camera.png'),color:Colors.white);
}
